-- ============================================================
-- MediCore HMS — Supabase PostgreSQL Sequences
-- Script 02: 02_sequences.sql
-- ============================================================

DROP SEQUENCE IF EXISTS user_seq CASCADE;
DROP SEQUENCE IF EXISTS department_seq CASCADE;
DROP SEQUENCE IF EXISTS patient_seq CASCADE;
DROP SEQUENCE IF EXISTS doctor_seq CASCADE;
DROP SEQUENCE IF EXISTS appointment_seq CASCADE;
DROP SEQUENCE IF EXISTS room_seq CASCADE;
DROP SEQUENCE IF EXISTS admission_seq CASCADE;
DROP SEQUENCE IF EXISTS medical_record_seq CASCADE;
DROP SEQUENCE IF EXISTS medicine_seq CASCADE;
DROP SEQUENCE IF EXISTS prescription_seq CASCADE;
DROP SEQUENCE IF EXISTS prescription_item_seq CASCADE;
DROP SEQUENCE IF EXISTS bill_seq CASCADE;
DROP SEQUENCE IF EXISTS bill_item_seq CASCADE;

CREATE SEQUENCE user_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE department_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE patient_seq START WITH 1001 INCREMENT BY 1;
CREATE SEQUENCE doctor_seq START WITH 2001 INCREMENT BY 1;
CREATE SEQUENCE appointment_seq START WITH 3001 INCREMENT BY 1;
CREATE SEQUENCE room_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE admission_seq START WITH 4001 INCREMENT BY 1;
CREATE SEQUENCE medical_record_seq START WITH 5001 INCREMENT BY 1;
CREATE SEQUENCE medicine_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE prescription_seq START WITH 6001 INCREMENT BY 1;
CREATE SEQUENCE prescription_item_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE bill_seq START WITH 7001 INCREMENT BY 1;
CREATE SEQUENCE bill_item_seq START WITH 1 INCREMENT BY 1;
